---
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender
no_index:
  directory:
    - inc
    - t
requires:
  Capture::Tiny: 0
  Carp: 0
  Class::Method::Modifiers: 0
  Cwd: 0
  Email::Abstract: 3
  Email::Address: 0
  Email::Simple: 1.998
  Fcntl: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  List::MoreUtils: 0
  Mouse: 0.12
  Net::SMTP: 0
  Scalar::Util: 0
  Sys::Hostname::Long: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
