---
abstract: 'a library for sending email'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender
requires:
  Capture::Tiny: 0
  Carp: 0
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  Email::Abstract: 3
  Email::Address: 0
  Email::Sender::Transport::SMTP_X: 0
  Email::Simple: 1.998
  Errno: 0
  Exporter: 0
  ExtUtils::MakeMaker: 6.11
  Fcntl: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  IO::File: 0
  IO::Handle: 0
  JSON: 0
  List::MoreUtils: 0
  Moose: 0.70
  Moose::Role: 0
  Net::SMTP: 0
  Net::SMTP::SSL: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Sub::Exporter::Util: 0
  Sub::Override: 0
  Sys::Hostname: 0
  Sys::Hostname::Long: 0
  Test::Email::SMTPRig: 0
  Test::Email::Sender::Util: 0
  Test::MinimumVersion: 0
  Test::MockObject: 0
  Test::More: 0
  Throwable::Error: 0.100090
  Try::Tiny: 0
resources:
  repository: git://git.codesimply.com/Email-Sender.git
version: 0.100450
